<?php

namespace SBC\CodeMakerBundle\Repository;

/**
 * GeneratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneratorRepository extends \Doctrine\ORM\EntityRepository
{
}
